include("resolving/test.jl")
include("splitgraph/test.jl")
include("main/test.jl")
include("SRG/test.jl")
include("NYdata/test.jl")
include("MultiTreeKnit_benchmark/test_benchmark.jl")
include("MultiTreeKnit_benchmark/test_measures.jl")
